#!/bin/bash

function runcmd
{
    echo "CMD: $@"
    sleep 0.2
    $@
    ret=$?
    if test $ret -ne 0 ; then
	exit $ret
    fi
}

runcmd ./bootstrap
#runcmd autoreconf -v -i
#runcmd /bin/rm -fr BUILD
runcmd mkdir -p BUILD
runcmd cd BUILD

# pass parameters to configure for linking with our libs
export CPPFLAGS="-I$HOME/lib/strace2ds/include"
export LDFLAGS="\
	-Xlinker -rpath=/usr/local/dataseries/lib:$HOME/lib/strace2ds/lib \
	-L/usr/local/dataseries/lib -L$HOME/lib/strace2ds/lib"
LIBS="-lstrace2ds -lLintel -lDataSeries"

# show configure command than run it
echo CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ../configure --enable-dataseries
CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" \
    ../configure --enable-dataseries || exit $?

# no need to make clean if you only changed source code here
runcmd make clean
# if all you changed is C code, you can "cd BUILD" and run the same
# make command below.
echo make LIBS="$LIBS" CCLD=g++
make LIBS="$LIBS" CCLD=g++ || exit $?
#runcmd make install

# example how to run new strace
# $ cd BUILD
# $ STRACE2DS=~/strace2ds ./strace -X foo.ds /bin/cat stamp-h
# ls -l foo.ds
